#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

docker run \
  --tty \
  --interactive \
  --user=$(id --user) \
  --env="DISPLAY" \
  --env="NO_AT_BRIDGE=1" \
  --ipc host \
  --workdir="$HOME" \
  --volume="$HOME:$HOME:rw" \
  --volume="/etc/localtime:/etc/localtime:ro" \
  --volume="/etc/timezone:/etc/timezone:ro" \
  --volume="/etc/group:/etc/group:ro" \
  --volume="/etc/passwd:/etc/passwd:ro" \
  --volume="/etc/shadow:/etc/shadow:ro" \
  --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
  --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
  --name jdownloader-installer
  dyokomizo/jdownloader-installer "$@"

docker commit --change 'CMD ["'$HOME'/jd2/JDownloader2"]' jdownloader-installer $USER/jdownloader
